id: IABBB1ECC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:51:30+00:00'
last_modified: '2022-06-09T04:45:39.580831+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20106
  title: མཐིང་གླིང་གཡུལ་འགྱེད་དཔའ་བོ་རྩལ་འགྲན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A374:
      image_group_id: I1KG18005
      title: Volume 1 of mthing gling g.yul 'gyed dpa' bo rtsal 'gran/
      total_pages: 252
      order: 1
      base_file: A374.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
