id: P008137
initial_creation_type: ocr
source_metadata:
  id: bdr:W20106
  title: མཐིང་གླིང་གཡུལ་འགྱེད་དཔའ་བོ་རྩལ་འགྲན།
  author: ''
  volumes:
    037d5c824515439dbcbc22d0de4f50a9:
      image_group_id: I1KG18005
      title: ''
      volume_number: 1
      total_pages: 252
ebook_metadata:
  title: མཐིང་གླིང་གཡུལ་འགྱེད་དཔའ་བོ་རྩལ་འགྲན།
  author: ''
  sku: P008137
  cover: cover.jpg
  layers:
  - pagination
