id: P008137
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20106
  title: མཐིང་གླིང་གཡུལ་འགྱེད་དཔའ་བོ་རྩལ་འགྲན།
  author: ''
  volumes:
    e9867a4630c248089ce8faefd29bf063:
      image_group_id: I1KG18005
      title: Volume 1 of mthing gling g.yul 'gyed dpa' bo rtsal 'gran/
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
